### ISSUE TITLE
UI Change Inputs

### ISSUE THREAD

**Issue by ajayellipsis** [ajayellipsis/Ellipsisaiv2#1]
@yvrangababu changes as discussed on the call. 

- Styling for each section under all tools page (All tools Listing Page)
- Icons for each tools
- Short description for each tool
- Top bar for hamburger menu (Logout, profile etc)
- Most Popular Tools - Create icon/ card approach for this
- On dashboard page - View all 
- Heading for Content Tools
- Dominant blue is #5433FF
- Lefthand Navigation bar - make it collapsable

**Comment by yvrangababu** [comment]
Creating separate issue for Icons and short description for all tools
